---
  - name: "update apt packages."
    become: true
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: true
    apt:
      upgrade: yes
    
  - name: install python
    become: true
    apt: 
      name: python3=2.7.3
      #state: present

  - name: install NodeJs
    become: true
    apt: 
      name: nodejs=13.8.0
      #state: present

  - name: install build essential
    become: true
    apt: 
      name: build-essential
      #state: present
  
  - name: install npm
    become: true
    apt: 
      name: npm=6.13.6
      #state: present
  
  - name: install PM2
    become: true
    shell: npm install pm2 -g
      
