---
  - name: "update apt packages."
    become: true
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: true
    apt:
      upgrade: yes
    
  - name: install python
    become: true
    apt: 
      name: python3
      state: present

  - name: install NodeJs
    become: true
    shell: |
      curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      sudo apt install -y nodejs
      sudo npm install -g n
      sudo n 13.8.0
      
  - name: install build essential
    become: true
    apt: 
      name: build-essential
      state: present
  
  - name: install npm
    become: true
    shell: npm install -g npm@6.13.6
      
  
  - name: install PM2
    become: true
    shell: npm install pm2 -g
      
