---
  - name: Copy files
    become: true
    copy:
      src: ~/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz
  - name: Unarchive
    become: true
    shell : |
        cd /home/ubuntu/
        tar -xvzf artifact.tar.gz -C .

  - name: "install dependancies"
    become: true
    shell : |
        npm install
        
  
  - name: "run server"
    become: true
    shell : |
        export TYPEORM_ENTITIES=./dist/modules/domain/**/*.entity{.ts,.js}
        export TYPEORM_HOST=database-1.chfm6ecrzmdb.us-east-1.rds.amazonaws.com
        export TYPEORM_PORT=5432
        export TYPEORM_USERNAME=postgres
        export TYPEORM_PASSWORD=mypassword
        export TYPEORM_DATABASE=postgres
        export TYPEORM_MIGRATIONS_DIR=./dist/migrations
        export TYPEORM_MIGRATIONS=./dist/migrations/*.ts
        npm i
        pm2 stop default
        pm2 start -f /home/ubuntu/dist/main.js
        # sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"